# Generated by Django 5.1.6 on 2025-03-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assidu", "0005_remove_country_country_iso_name_city_city_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
    ]
