# Generated by Django 5.1.6 on 2025-03-03 01:48

import assidu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assidu", "0006_alter_city_options_alter_country_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="some_number",
            field=models.IntegerField(
                default=1,
                validators=[
                    assidu.models.validate_even,
                    assidu.models.divisible_by_seven,
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="city",
            name="area_sq_km",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    assidu.models.validate_even,
                    assidu.models.divisible_by_seven,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="date_of_last_mayoral_election",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="elevation_metres",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
