# Generated by Django 5.1.6 on 2025-03-03 01:50

import assidu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assidu", "0007_city_some_number_alter_city_area_sq_km_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="some_number",
            field=models.IntegerField(
                blank=True,
                validators=[
                    assidu.models.validate_even,
                    assidu.models.validate_not_divisible_by_seven,
                ],
            ),
        ),
    ]
