# Generated by Django 5.1.6 on 2025-03-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assidu", "0010_alter_city_area_sq_km"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="some_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
